language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
notifications:
  email: false
script:
- npm run format:check
- npm run tslint
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: maxime.kjaer@gmail.com
  api_key:
    secure: PLy5Ud4b9OU5KFLRsQRchZn7KnWDruDDOoxpdJrl23j5LN3b5r7fsb42I2lV03eY42lxbkH7vzPC4CZUyhdkkYhrjqHBTEACYQfD/7q82SlHip/6NqKvXn0XddEFGUuPu9zFyv2Hv5E3ZYMoVccJ8JFikLljWWLznTmlyvezJaFMIQHeCJgQmiW7ZudaTT9zLMV2TQ2jpFvXHyslXSjxCaF1eYNVTWN6vwYZIzEpCWAifNzdNcDunfFMZkzIDroPsM+EU17Cy3cT+fmZam6TWB7P+6mOlZRLVFw2b1tm4rvwQrHf0+SBbmb8RIcFt9ZGLgF8pygxkrMB42iyyzA/H9yC6qhV0D9MDv9NP36AW1gpnPOswvtvCOA2l+g0J8tvOCy50gZFImPLGch8DtVOHB1SRckeShpKApnmvClMhYO85dpyYtjl8jYLVfK8KpudJJMdJ/mk2C32faV6/OM4EQFBYAt52WCxDIHRT0Nr26MjDOQ3Kc7apSt+p3JEzg4d5vEDe2L5aGAJDsfrlKQ9OYxdy55kwwvafWIHt2VUXPoOIFXHo0ToVJ1+0CuEb7hSYig7JY51kPekLLEgGin89TxZY1oXAUOR+H4Ja5lRKw8w8KM5jORi/Cst7pJA/VTIQwX6I/fL01h25ee7f9jf6TA6sAMxJhn7hWtnSeyneKc=
  on:
    tags: true
    repo: "hashmark-lang/hashmark-parser"
