/* This file was generated by Hashml https://github.com/hashml/hashml */
export type Tag = BlockTag | InlineTag;
export type BlockTag = BlockRoot | BlockParagraph | BlockSection | BlockId | BlockCode;
export type InlineTag = InlineLink | InlineBold | InlineStrong | InlineCode | InlineInline;
export interface BlockRoot {
    $tag: "root";
    content: (BlockParagraph | BlockSection | BlockCode)[];
}
export interface BlockParagraph {
    $tag: "paragraph";
    text: (InlineLink | InlineBold | InlineCode | InlineStrong | InlineInline | string)[];
}
export interface BlockSection {
    $tag: "section";
    content: (BlockParagraph | BlockSection | BlockCode)[];
    id: BlockId | null;
    title: (InlineLink | InlineBold | InlineCode | InlineStrong | InlineInline | string)[];
}
export interface BlockId {
    $tag: "id";
    content: string;
}
export interface BlockCode {
    $tag: "code";
    content: string[];
    language: string;
}
export interface InlineLink {
    $tag: "link";
    url: URL;
    text: (InlineBold | string)[];
}
export interface InlineBold {
    $tag: "bold";
    text: (InlineLink | string)[];
}
export interface InlineStrong {
    $tag: "strong";
    text: (InlineLink | string)[];
}
export interface InlineCode {
    $tag: "code";
    content: string;
}
export interface InlineInline {
    $tag: "inline";
    inlineContent: (InlineLink | InlineBold | InlineCode | InlineStrong | InlineInline | string)[];
}
