/* This file was generated by Hashml https://github.com/hashml/hashml */
export interface Root {
    $tag: "root";
}
export type Tag = BlockTag | InlineTag;
export type BlockTag = never;
export type InlineTag = never;
